# This is the config file for building and testing Geo::OGC::Service::WFS with Travis-ci.org

language: perl
perl:
  - "5.22.0"

before_install:
  - sudo apt-get install libexpat-dev libpq-dev 

install:
  - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .

script: "perl Makefile.PL; .make test"

branches:
  only:
    - master

notifications:
  recipients:
    - ari.jolma@gmail.com
  email:
    on_success: change
    on_failure: always
